### ISSUE TITLE
PyPI: add logo to site

### ISSUE THREAD

**Issue by lsimonsen** [macrosynergy/macrosynergy#506]
In our README.md file we have the Macrosynergy logo at the top. For the [PyPI page](https://pypi.org/project/macrosynergy/) it disappears. Figure out how to re-add it.

**Comment by Magnus167** [comment]
The readme uses a ["local" reference to the repository](https://github.com/macrosynergy/macrosynergy/blob/fc3771447eb593e068b3c1ea43493b9410b555d9/README.md?plain=1#L1) i.e. `docs/source/_static/MACROSYNERGY_Logo_Primary.png` to the image.
We should try replacing it with its raw.githubusercontent... link i.e. [`https://raw.githubusercontent.com/macrosynergy/macrosynergy/develop/docs/source/_static/MACROSYNERGY_Logo_Primary.png?raw=True`](https://raw.githubusercontent.com/macrosynergy/macrosynergy/develop/docs/source/_static/MACROSYNERGY_Logo_Primary.png?raw=True). 
Since this is the link to the image file itself, instead of a reference, it should work.
